import Link from "next/link";
import { notFound } from "next/navigation";
import { getCustomer, getShopName } from "@/lib/actions/credit";
import { formatTZS, formatDate } from "@/lib/currency";
import { buildWhatsAppLink } from "@/lib/whatsapp";
import { PrintButton } from "@/components/credit/PrintButton";

export default async function StatementPage(
  props: PageProps<"/app/credit/[customerId]/statement">
) {
  const { customerId } = await props.params;

  let data: Awaited<ReturnType<typeof getCustomer>>;
  try {
    data = await getCustomer(customerId);
  } catch {
    notFound();
  }
  const { customer, ledger } = data;
  const shopName = await getShopName();

  const chronological = [...ledger].sort((a, b) => (a.at > b.at ? 1 : -1));
  const rows = chronological.reduce<Array<(typeof chronological)[number] & { runningBalance: number }>>(
    (acc, row) => {
      const prevBalance = acc.length ? acc[acc.length - 1].runningBalance : 0;
      const runningBalance = prevBalance + (row.kind === "credit" ? row.amount : -row.amount);
      acc.push({ ...row, runningBalance });
      return acc;
    },
    []
  );

  const generatedOn = formatDate(new Date().toISOString());
  const shareMessage = `Account statement from ${shopName} for ${customer.name}: outstanding balance ${formatTZS(
    customer.balance
  )} as of ${generatedOn}.`;

  return (
    <div className="mx-auto max-w-xl px-4 py-8 sm:px-6 print:max-w-none print:px-0 print:py-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <Link
          href={`/app/credit/${customerId}`}
          className="text-sm text-ink-soft hover:text-ink"
        >
          &larr; Back to ledger
        </Link>
        <div className="flex gap-2">
          <a href={buildWhatsAppLink(customer.phone, shareMessage)} target="_blank" rel="noopener noreferrer">
            <button
              type="button"
              className="inline-flex items-center justify-center rounded-[var(--radius-sm)] bg-positive px-4 py-2.5 text-sm font-medium text-paper-raised hover:brightness-95"
            >
              Share via WhatsApp
            </button>
          </a>
          <PrintButton />
        </div>
      </div>

      <div className="rounded-[var(--radius-lg)] border border-rule bg-paper-raised p-8 shadow-[var(--shadow-card)] print:border-0 print:p-0 print:shadow-none">
        <div className="flex items-start justify-between border-b border-rule pb-4">
          <div>
            <p className="font-serif text-lg font-medium text-ink">{shopName}</p>
            <p className="text-xs text-ink-faint">Account statement</p>
          </div>
          <p className="text-xs text-ink-faint">{generatedOn}</p>
        </div>

        <div className="mt-4 flex items-start justify-between">
          <div>
            <p className="font-medium text-ink">{customer.name}</p>
            <p className="tabular text-sm text-ink-soft">{customer.phone}</p>
          </div>
          <div className="text-right">
            <p className="text-xs uppercase tracking-wide text-ink-soft">Balance</p>
            <p
              className={`tabular font-serif text-2xl font-medium ${
                customer.balance > 0 ? "text-negative" : "text-positive"
              }`}
            >
              {formatTZS(customer.balance)}
            </p>
          </div>
        </div>

        <div className="ledger-lines mt-6 overflow-hidden rounded-[var(--radius-md)] border border-rule">
          {rows.length === 0 ? (
            <p className="px-4 py-8 text-center text-sm text-ink-faint">No entries yet.</p>
          ) : (
            rows.map((row) => (
              <div
                key={`${row.kind}-${row.id}`}
                className="flex items-center justify-between gap-3 px-4 py-[7px] text-sm"
              >
                <div className="min-w-0">
                  <p className="truncate text-ink">
                    {row.detail ?? (row.kind === "credit" ? "Credit sale" : "Payment received")}
                  </p>
                  <p className="text-xs text-ink-faint">{formatDate(row.date)}</p>
                </div>
                <div className="shrink-0 text-right">
                  <p
                    className={`tabular font-medium ${
                      row.kind === "credit" ? "text-negative" : "text-positive"
                    }`}
                  >
                    {row.kind === "credit" ? "+" : "−"}
                    {formatTZS(row.amount)}
                  </p>
                  <p className="tabular text-xs text-ink-faint">{formatTZS(row.runningBalance)}</p>
                </div>
              </div>
            ))
          )}
        </div>

        <p className="mt-6 text-center text-xs text-ink-faint">
          Generated by Tanzania Business OS on behalf of {shopName}.
        </p>
      </div>
    </div>
  );
}
